#!/bin/sh

export AFNMRHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

$AFNMRHOME/bin/teLeap \
           -I$AFNMRHOME/dat/leap/prep \
           -I$AFNMRHOME/dat/leap/lib \
           -I$AFNMRHOME/dat/leap/parm \
           -I$AFNMRHOME/dat/leap/cmd \
            $*
