#!/bin/bash
#
#    make a tar file for users
#
CWD=`pwd`
h=afnmr-1.1
tarfile=$h.tar
TARC="gnutar cf $tarfile"
TAR="gnutar rf $tarfile"

cd ..
ln -s $CWD $h
$TARC $h/{LICENSE,Makefile,basis,dat,doc/afnmr.pdf,mkdirs,src,test}
bzip2 -v $tarfile
/bin/rm $h

