#!/bin/bash
#
#    make a tar file for users
#
CWD=`pwd`
h=afnmr-1.0b1
tarfile=$h.tar
TARC="gnutar cfX $tarfile $CWD/excludes"
TAR="gnutar rfX $tarfile $CWD/excludes"

cd ..
ln -s $CWD $h
$TARC $h/*
bzip2 -v $tarfile
/bin/rm $h

