This file will attempt to document new features and changes in the
periodic 3D-RISM code as development occurs.

Note that this file is in Org format, a simple markup language used by
org-mode in Emacs.  For a brief introduction, please see [[http://orgmode.org/worg/org-tutorials/org4beginners.html][the org-mode
tutorial]].  It can be converted into almost every other format
imaginable using [[http://orgmode.org/worg/org-tutorials/org4beginners.htmlhttp://johnmacfarlane.net/pandoc/][pandoc]].

* Input
To indicate a 3D-RISM calculation is periodic, a new '--periodic'
input flag was added.
* Output
Nearly all data labels were changed to clarify their meaning. The
table below shows the new label and its predecessor.
| old label   | new label                 |
|-------------+---------------------------|
| solute_epot | solutePotentialEnergy     |
| exchem      | excessChemicalPotential   |
| exchGF      | excessChemicalPotentialGF |
| exchUC      | excessChemicalPotentialUC |
| potUV       | solventPotentialEnergy    |
| volume      | partialMolarVolume        |
| exNumb      | excessParticles           |
| exChrg      | excessCharge              |
| KB          | KirkwoodBuff              |
| DCFI        | DCFintegral               |
| pol         | polar                     |
| apol        | apolar                    |
| solvEne     | solvationEnergy           |

Several new fields were added to standard output.
- rism_totalParticles: total number of solvent atoms in the system.
- rism_totalCharge: total solvent charge in the system.
- rism_excessParticles: difference in number of solvent atoms in the
  system beyond that expected from bulk density.
- rism_excessCharge: difference in charge of solvent in the system
  beyond that expected from bulk density.
- rism_totalParticlesCorrected: total number of solvent atoms in the
  system, corrected using the long range asymptotics of the total
  correlation function.
- rism_totalChargeCorrected: total solvent charge in the system,
  corrected using the long range asymptotics of the total correlation
  function.
- rism_bulkCharge: total solvent charge expected in the system
  assuming the volume is fully occupied by bulk solvent. Primarily
  useful for debugging.
- rism_excessNumberCorrected: difference in number of solvent atoms in
  the system beyond that expected from bulk density, corrected using
  the long range asymptotics of the total correlation function.
- rism_excessChargeCorrected: difference in charge of solvent in the
  system from that expected from bulk density, corrected using the
  long range asymptotics of the total correlation function.
* Smeared electron density map
Smeared electron density maps for water solvent can be created with
the '--electronMap' flag. This smearing procedure combines the the
3D-RISM RDF with a theoretical 1D electron density RDF for water
oxygen. Support for more solvent varieties than water will be added in
the future.
* Doxygen comments
Doxygen documentation was added throughout the codebase. The Doxygen
documentation manual can be built using 'make doc'.
* Compilation
rism3d.snglpnt can now be built separately, which is much faster than
recompiling all of Amber. 
Usage: make -C AmberTools/src/rism rism3d.snglpnt install
Note that this will not work if amber_rism_interface is modified since
that would necessitate rebuiliding sander.
