#!/bin/zsh

# script to collect individual afnmr rdb files into an "rdball" file

# edit the id and the number of files below; this script assumes that each
#   snapshot was analyzed in a separated folder.

id=2jxs

foreach i ({1..50}) do
    echo $i
    cd $i
	make-shiftsrdb -orca ref_seg1_rattle ${id}.$i
	perl -p -i -e"s/${id}.${i}_shift/${id}.$i/" ${id}.$i.rdb
	column < ${id}.$i.rdb ${id}.$i > ../${id}.$i.rdbs
    cd ..
done

column < 1/${id}.1.rdb res atomname resname > keys

paste keys ${id}.{1..50}.rdbs > ${id}.rdball

#  Note: it is a good idea to run "wc *.rdbs" (before the cleanup step
#    below), to ensure that each file has the same number of rows.  If not,
#    something has gone wrong that needs to be investigated.

# /bin/rm ${id}*.rdbs keys
