#!/bin/bash

#------------------------------------------------------------------------------
#  set up usage statement:
#------------------------------------------------------------------------------
usage(){
cat<<EOD

Usage: make-shiftsrdb qpgm reference <basename>

   where qpgm must be one of "-demon", "-g09" or "-orca"
   reference is the name of a reference shielding set

   Input are <basename>xxx.{out,log} files
   Output goes to <basename>.rdb

EOD
}

check_afnmrhome() {
   if [ -z "$AFNMRHOME" ]; then
      echo ""
      echo "Your AFNMRHOME environment variable is not set!"
      exit 1
   fi
}

#------------------------------------------------------------------------------
#  Checking Arguments:
#------------------------------------------------------------------------------

check_afnmrhome

if [ $# -ne 3 ]; then usage; exit 1;  fi

case "$1" in
        -demon)       program="demon";;
        -orca)        program="orca";;
        -g09)         program="g09";;
        -help)        usage; exit 0;;
        --help)       usage; exit 0;;
        -h)           usage; exit 0;;

        -*) echo "Error: unknown flag: $1"
            usage
            exit 1;;
esac

reference=$2
basename=$3

#  header:
getshifts-$program $reference header > $basename.rdb

#  body:
if [ "$program" = "demon" -o "$program" = "orca" ]
then
    for i in ${basename}???.out
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} >> $basename.rdbi
    done
elif [ "$program" = "g09" ]; then
    for i in ${basename}???.log
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} >> $basename.rdbi
    done
fi

#  now sort the shifts by residue and atom name:
sort -k1n -k2 $basename.rdbi >> $basename.rdb
/bin/rm $basename.rdbi
