#!/bin/bash

#------------------------------------------------------------------------------
#  set up usage statement:
#------------------------------------------------------------------------------
usage(){
cat<<EOD

Usage: make-shiftsrdb qpgm reference <basename> fulltensor

   * qpgm must be one of "-demon", "-gau", "-qchem", "-jaguar" or "-orca"
   * reference is the name of a reference shielding set
        The reference sets are defined in the getshifts-demon (etc.)
        scripts,  and sometimes change as better sets beccome available.  
        Users can create their own versions.
   * quantum outputs are assumed to be in <basename>nnn.{out,log,qcout}
        files, where "nnn" is a three-digit resiude number (such as "001")
   * fulltensor is 1 to get expanded CSA printouts, 0 otherwise

   Output goes to <basename>.rdb

EOD
}

check_afnmrhome() {
   if [ -z "$AFNMRHOME" ]; then
      echo ""
      echo "Your AFNMRHOME environment variable is not set!"
      exit 1
   fi
}

#------------------------------------------------------------------------------
#  Checking Arguments:
#------------------------------------------------------------------------------

check_afnmrhome

if [ $# -lt 4 ]; then usage; exit 1;  fi

case "$1" in
        -demon)       program="demon";;
        -orca)        program="orca";;
        -gau)         program="gau";;
        -qchem)       program="qchem";;
        -jaguar)      program="jaguar";;
        -help)        usage; exit 0;;
        --help)       usage; exit 0;;
        -h)           usage; exit 0;;

        -*) echo "Error: unknown flag: $1"
            usage
            exit 1;;
esac

reference=$2
basename=$3
if [ "x$4" == "x" ]; then
   fulltensor = 0
else
   fulltensor=$4
fi

#  header:
getshifts-$program $reference header $fulltensor > $basename.rdb

#  body:
if [ "$program" = "demon" -o "$program" = "orca" ]
then
    for i in ${basename}???.out
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} $fulltensor >> $basename.rdbi
    done
elif [ "$program" = "gau" ]; then
    for i in ${basename}???.log
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} $fulltensor >> $basename.rdbi
    done
elif [ "$program" = "qchem" ]; then
    for i in ${basename}???.qcout
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} $fulltensor >> $basename.rdbi
    done
elif [ "$program" = "jaguar" ]; then
    for i in ${basename}???.out
    do
        $AFNMRHOME/bin/getshifts-$program $reference ${i%.*} >> $basename.rdbi
    done
fi

#  now sort the shifts by residue and atom name:
#    the tr kludge seems needed since (some) Linux sorts do not treat "'"
#    in a consistent way.  Assumes that "z" will not appear in an atomname
tr "'" "z" < $basename.rdbi | sort -k1n -k2 | tr "z" "'" >> $basename.rdb
/bin/rm $basename.rdbi
