#!/usr/bin/perl
#
#  convert the "xyz" output from orca to a pdb file
#    arguments are xyz file, pdb template file; output to stdout
#
open( XYZ, "$ARGV[0]" ) || die "can't find input file $ARGV[0]\n" ;
<XYZ>; <XYZ>;  # skip 2 line header
while ($_ = <XYZ>) {
	$i++;
	($ano, $x[$i], $y[$i], $z[$i]) = split(' ', $_ );
}
close( XYZ );

open( PDB, "$ARGV[1]" ) || die "can't find file template\n" ;
for $j (1..$i){
	$_ = <PDB>; printf STDOUT "%30s%8.3f%8.3f%8.3f%24s\n", substr($_,0,30),
		$x[$j], $y[$j], $z[$j], substr($_,54,24);
}
