#   top-level Makefile for afnmr
install: 
	(cd leap && make install )
	(cd etc && make ambpdb )
	(cd sff && make install )
	(cd MEAD && make install)
	(cd afnmr && make install)

clean::
	-(cd leap && make clean )
	-(cd etc && make clean )
	-(cd sff && make clean )
	-(cd MEAD && make clean)
	-(cd afnmr && make clean)

